/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int LEFT = 12;
  /** RegularExpression Id. */
  int FRONT = 13;
  /** RegularExpression Id. */
  int BACK = 14;
  /** RegularExpression Id. */
  int AROUND = 15;
  /** RegularExpression Id. */
  int BALLOONS = 16;
  /** RegularExpression Id. */
  int CHIPS = 17;
  /** RegularExpression Id. */
  int REPEAT = 18;
  /** RegularExpression Id. */
  int NORTH = 19;
  /** RegularExpression Id. */
  int SOUTH = 20;
  /** RegularExpression Id. */
  int EAST = 21;
  /** RegularExpression Id. */
  int WEST = 22;
  /** RegularExpression Id. */
  int DIM = 23;
  /** RegularExpression Id. */
  int MYXPOS = 24;
  /** RegularExpression Id. */
  int MYYPOS = 25;
  /** RegularExpression Id. */
  int MYCHIPS = 26;
  /** RegularExpression Id. */
  int MYBALLOONS = 27;
  /** RegularExpression Id. */
  int BALLOONSHERE = 28;
  /** RegularExpression Id. */
  int CHIPSHERE = 29;
  /** RegularExpression Id. */
  int SPACES = 30;
  /** RegularExpression Id. */
  int MOVE = 31;
  /** RegularExpression Id. */
  int EQUAL = 32;
  /** RegularExpression Id. */
  int DEFVAR = 33;
  /** RegularExpression Id. */
  int TURN = 34;
  /** RegularExpression Id. */
  int FACE = 35;
  /** RegularExpression Id. */
  int MOVEDIR = 36;
  /** RegularExpression Id. */
  int RUNDIRS = 37;
  /** RegularExpression Id. */
  int MOVEFACE = 38;
  /** RegularExpression Id. */
  int NULL = 39;
  /** RegularExpression Id. */
  int DEFUN = 40;
  /** RegularExpression Id. */
  int RBRACKET = 41;
  /** RegularExpression Id. */
  int LBRACKET = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int FACING = 44;
  /** RegularExpression Id. */
  int BLOCKED = 45;
  /** RegularExpression Id. */
  int CANPUT = 46;
  /** RegularExpression Id. */
  int CANPICK = 47;
  /** RegularExpression Id. */
  int CANMOVE = 48;
  /** RegularExpression Id. */
  int ISZERO = 49;
  /** RegularExpression Id. */
  int NOT = 50;
  /** RegularExpression Id. */
  int NAME = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int NUMS = 53;
  /** RegularExpression Id. */
  int NUM = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int INITIALDIGIT = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\":right\"",
    "\"put\"",
    "\"pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"skip\"",
    "\":left\"",
    "\":front\"",
    "\":back\"",
    "\":around\"",
    "\":ballons\"",
    "\":chips\"",
    "\"repeat\"",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "\"Dim\"",
    "\"myXpos\"",
    "\"myYpos\"",
    "\"myChips\"",
    "\"myBalloons\"",
    "\"balloonsHere\"",
    "\"ChipsHere\"",
    "\"Spaces\"",
    "\"move\"",
    "\"=\"",
    "\"defvar\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"null\"",
    "\"defun\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"facing?\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"isZero?\"",
    "\"not\"",
    "<NAME>",
    "<LETTER>",
    "<NUMS>",
    "<NUM>",
    "<DIGIT>",
    "<INITIALDIGIT>",
    "\",\"",
  };

}
