/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RIGHT = 5;
  /** RegularExpression Id. */
  int LEFT = 6;
  /** RegularExpression Id. */
  int FRONT = 7;
  /** RegularExpression Id. */
  int BACK = 8;
  /** RegularExpression Id. */
  int AROUND = 9;
  /** RegularExpression Id. */
  int BALLOONS = 10;
  /** RegularExpression Id. */
  int CHIPS = 11;
  /** RegularExpression Id. */
  int REPEAT = 12;
  /** RegularExpression Id. */
  int LOOP = 13;
  /** RegularExpression Id. */
  int NORTH = 14;
  /** RegularExpression Id. */
  int SOUTH = 15;
  /** RegularExpression Id. */
  int EAST = 16;
  /** RegularExpression Id. */
  int WEST = 17;
  /** RegularExpression Id. */
  int DIM = 18;
  /** RegularExpression Id. */
  int MYXPOS = 19;
  /** RegularExpression Id. */
  int MYYPOS = 20;
  /** RegularExpression Id. */
  int MYCHIPS = 21;
  /** RegularExpression Id. */
  int MYBALLOONS = 22;
  /** RegularExpression Id. */
  int BALLOONSHERE = 23;
  /** RegularExpression Id. */
  int CHIPSHERE = 24;
  /** RegularExpression Id. */
  int SPACES = 25;
  /** RegularExpression Id. */
  int MOVE = 26;
  /** RegularExpression Id. */
  int EQUAL = 27;
  /** RegularExpression Id. */
  int DEFVAR = 28;
  /** RegularExpression Id. */
  int TURN = 29;
  /** RegularExpression Id. */
  int FACE = 30;
  /** RegularExpression Id. */
  int MOVEDIR = 31;
  /** RegularExpression Id. */
  int RUNDIRS = 32;
  /** RegularExpression Id. */
  int MOVEFACE = 33;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int PUT = 35;
  /** RegularExpression Id. */
  int PICK = 36;
  /** RegularExpression Id. */
  int HOP = 37;
  /** RegularExpression Id. */
  int DEFUN = 38;
  /** RegularExpression Id. */
  int RBRACKET = 39;
  /** RegularExpression Id. */
  int LBRACKET = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int FACING = 42;
  /** RegularExpression Id. */
  int BLOCKED = 43;
  /** RegularExpression Id. */
  int CANPUT = 44;
  /** RegularExpression Id. */
  int CANPICK = 45;
  /** RegularExpression Id. */
  int CANMOVE = 46;
  /** RegularExpression Id. */
  int ISZERO = 47;
  /** RegularExpression Id. */
  int NOT = 48;
  /** RegularExpression Id. */
  int NAME = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int NUMS = 51;
  /** RegularExpression Id. */
  int NUM = 52;
  /** RegularExpression Id. */
  int DIGIT = 53;
  /** RegularExpression Id. */
  int INITIALDIGIT = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":right\"",
    "\":left\"",
    "\":front\"",
    "\":back\"",
    "\":around\"",
    "\":balloons\"",
    "\":chips\"",
    "\"repeat\"",
    "\"loop\"",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "\"Dim\"",
    "\"myXpos\"",
    "\"myYpos\"",
    "\"myChips\"",
    "\"myBalloons\"",
    "\"balloonsHere\"",
    "\"ChipsHere\"",
    "\"Spaces\"",
    "\"move\"",
    "\"=\"",
    "\"defvar\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"null\"",
    "\"put\"",
    "\"pick\"",
    "\"skip\"",
    "\"defun\"",
    "\")\"",
    "\"(\"",
    "\"if\"",
    "\"facing?\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"isZero?\"",
    "\"not\"",
    "<NAME>",
    "<LETTER>",
    "<NUMS>",
    "<NUM>",
    "<DIGIT>",
    "<INITIALDIGIT>",
    "\",\"",
  };

}
